name: simulation
channels:
 - conda-forge
 - defaults
 - r
 - bioconda
dependencies:
 - python=3.5
 - snakemake=3.9.1
 - curl=7.45.0
 - bedtools=2.26.0
 - htslib=1.3.2
 - ruby=2.2.2
 - samtools=1.3.1
 - bcftools=1.3.1
